version: "3.9"
services:
    mariadb:
        image: "postgres:13.3"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./entrypoint:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=temsys
            - POSTGRES_USER=temsys
            - POSTGRES_PASSWORD=temsys
