services:
    web:
        build: .
        restart: on-failure
        ports:
            - "3000:3000"
        links:
            - mariadb
        depends_on:
            - mariadb
        environment:
            - CONFIG_DBNAME=temsys:temsys@tcp(mariadb:3306)/temsys
            - CONFIG_URL=0.0.0.0:3000
            - CONFIG_JWTKEY=blablamykeyblabla
            - CONFIG_DBDRIVER=mysql
            - CONFIG_CORS=localhost:3000
        volumes:
            - ./temsysdata:/data

    mariadb:
      image: "postgres:13.3"
        restart: always
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./entrypoint:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=temsys
            - POSTGRES_USER=temsys
            - POSTGRES_PASSWORD=temsys
