services:
    web:
        build: .
        restart: on-failure
        ports:
            - "3000:3000"
        links:
            - mariadb
        depends_on:
            - mariadb
        environment:
            - CONFIG_DBNAME=temsys:temsys@tcp(mariadb:3306)/temsys
            - CONFIG_URL=0.0.0.0:3000
            - CONFIG_JWTKEY=blablamykeyblabla
            - CONFIG_DBDRIVER=mysql
            - CONFIG_CORS=localhost:3000
        volumes:
            - ./temsysdata:/data

    mariadb:
        image: "mariadb:10.5.8-focal"
        restart: always
        volumes:
            - ./db:/var/lib/mysql
            - ./entrypoint:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=temsys
            - MYSQL_USER=temsys
            - MYSQL_PASSWORD=temsys