USE tempanalizr;

CREATE TABLE REPORT_TYPES (
    TYPE_NAME VARCHAR(255) PRIMARY KEY
);

CREATE TABLE SENSORS (
	NAME VARCHAR(255) PRIMARY KEY,
	CONNTYPE VARCHAR(255) NOT NULL,
	CONNVALUE VARCHAR(255) NOT NULL,
    UPDATE_INTERVAL INTEGER NOT NULL,
	DELETED BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE USED_REPORT_TYPES (
	SENSOR VARCHAR(255) NOT NULL,
    REPORT_TYPE VARCHAR(255) NOT NULL,
	ADD_DATE DATETIME(3)
);

CREATE TABLE REPORTS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	SENSOR VARCHAR(255),
	TYPE VARCHAR(255) NOT NULL,
	VALUE FLOAT NOT NULL,
	REPORT_DATE DATETIME(3)
);

ALTER TABLE REPORTS ADD CONSTRAINT FOREIGN KEY (SENSOR) REFERENCES SENSORS(NAME);
ALTER TABLE REPORTS ADD CONSTRAINT FOREIGN KEY (TYPE) REFERENCES REPORT_TYPES(TYPE_NAME);
ALTER TABLE USED_REPORT_TYPES ADD CONSTRAINT PRIMARY KEY (SENSOR, REPORT_TYPE);
ALTER TABLE USED_REPORT_TYPES ADD CONSTRAINT FOREIGN KEY (SENSOR) REFERENCES SENSORS(NAME);
ALTER TABLE USED_REPORT_TYPES ADD CONSTRAINT FOREIGN KEY (REPORT_TYPE) REFERENCES REPORT_TYPES(TYPE_NAME);
