version: '3'
services:
    api:
        build: .
        ports:
            - 8080:8080
        restart: always
        links:
            - db
        depends_on:
            - db
        environment:
            - TEMPDBPASS=${MYSQL_ROOT_PASSWORD}
        external_links: 
            - temprabbit:rabbit
        networks:
            - default
            - temprabbitnet
    db:
        image: mysql:8.0.19
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=tempanalizr
        volumes:
            - "./sapidata:/var/lib/mysql"
            - "./db/container.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
    temprabbitnet:
        external: true