DROP TABLE IF EXISTS REPORTS;

CREATE TABLE REPORTS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SENSOR VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL,
    VALUE FLOAT NOT NULL,
    REPORT_DATE DATETIME(3)
);