version: '3'
services:
    api:
        build: .
        ports:
            - 8081:8081
        restart: always
        links:
            - temapidb
        depends_on:
            - temapidb
        external_links:
            - temprabbit:rabbit
        networks:
            - default
            - temprabbitnet
            - sensorapi_default
    temapidb:
        image: mysql:5.7.29
        command: "--innodb_use_native_aio=0"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tempanalizr
        volumes:
            - "./temapidata:/var/lib/mysql"
            - "./db/container.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
    temprabbitnet:
        external: true
    sensorapi_default:
        external: true